#!/bin/bash

export UNICODE_FONT=true
export PROMPT_TEXT="  " #"  "  #  " ##"ᐉ "
export PROMPT_PREFIX="  "
export CLOCK_ICON=""
export CALENDAR_ICON=" "
export FOLDER_ICON="  "
export HOME_ICON=""
export USER_ICON=""
export SERVER_ICON=" "
export SESSION_ICON="  "
export NETWORK_ICON=" "
export DRIVE_ICON=""
export COMMAND_ICON="ﬦ"
export LOCK_ICON=""
export PREFIX_ICON="גּ"
export ZOOM_ICON=""
export SYNC_ICON="ﳳ"
export GIT_ICON=""
export LINE_ICON=""
export COLUMN_ICON=""
export POWERLINE_FILLED_LEFT=""
export POWERLINE_FILLED_RIGHT=""
export POWERLINE_LEFT=""
export POWERLINE_RIGHT=""
