- hosts: localhost
  tasks:

  - name: symlink dotfiles
    file:
      src: "{{ lookup('env', 'HOME') }}/.dotfiles/files/{{ item }}"
      path: "{{ lookup('env', 'HOME') }}/.{{ item }}"
      state: link
    with_items: [profile, bashrc, inputrc, tmux.conf, gitignore]

  - name: configure gitignore
    command: git config --global core.excludesfile {{ lookup('env', 'HOME') }}/.gitignore

  - name: create nvim directory
    file:
      path: "{{ lookup('env', 'HOME') }}/.config/nvim/autoload"
      state: directory

  - name: symlink init.vim
    file:
      src: "{{ lookup('env', 'HOME') }}/.dotfiles/files/init.vim"
      path: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"
      state: link

  - name: download vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: "{{ lookup('env', 'HOME') }}/.config/nvim/autoload/plug.vim"

  - name: install mdvl markdown viewer
    command: pipx install mdvl  

  - name: install homebrew packages
    community.general.homebrew:
      name: "{{ item }}"
    with_items: [gcc, python3, neovim, tmux, npm]

  - name: install neovim python3 module
    pip:
      extra_args: '--upgrade'
      name: pynvim

  - name: install neovim npm package
    community.general.npm:
      global: yes
      name: neovim

  - name: install neovim ruby package
    community.general.gem:
      name: neovim
