#!/bin/bash

# prompt_to_replace <file-in-current-dir> <abs-path-to-replace>
function prompt_to_replace() {
	if [ -L "$2" ]; then
		rm $2;
	elif [ -f "$2" ]; then
		read -p "Replace regular file '$2' with symlink to '$1? " yn
		case $yn in
			y) rm $2 ;;
			*) return 1 ;;
		esac
	elif [ -d "$2" ]; then
		read -p "Replace directory '$2' with symlink to '$1? " yn
		case $yn in
			y) rm -rf $2 ;;
			*) return 1 ;;
		esac
	fi
	ln -s $PWD/$1 $2
}

mkdir -p "$HOME/.config/vis"
mkdir -p "$HOME/.config/vis/plugins"

if [ ! -f "$HOME/.config/vis/plugins/vis-filetype-settings.lua" ]; then
	wget https://raw.githubusercontent.com/jocap/vis-filetype-settings/master/vis-filetype-settings.lua \
		-O "$HOME/.config/vis/plugins/vis-filetype-settings.lua" --no-check-certificate
fi

mkdir -p "$HOME/.config/nvim"
mkdir -p "$HOME/.config/nvim/colors"

if [ ! -f "$HOME/.config/nvim/colors/zenburn.vim" ]; then
	wget https://raw.githubusercontent.com/jnurmine/Zenburn/master/colors/zenburn.vim \
		-O "$HOME/.config/nvim/colors/zenburn.vim" --no-check-certificate
fi


prompt_to_replace bashrc      $HOME/.bashrc
prompt_to_replace inputrc     $HOME/.inputrc
prompt_to_replace tmux.conf   $HOME/.tmux.conf
prompt_to_replace tmux.local  $HOME/.tmux.local
prompt_to_replace gdbinit     $HOME/.gdbinit
prompt_to_replace conkyrc     $HOME/.conkyrc
prompt_to_replace visrc.lua   $HOME/.config/vis/visrc.lua
prompt_to_replace init.vim    $HOME/.config/nvim/init.vim
