#!/bin/bash

# prompt_to_replace <file-in-current-dir> <abs-path-to-replace>
function prompt_to_replace() {
	if [ -L "$2" ]; then
		rm $2;
	elif [ -f "$2" ]; then
		read -p "Replace regular file '$2' with symlink to '$1? " yn
		case $yn in
			y) rm $2 ;;
			*) return 1 ;;
		esac
	elif [ -d "$2" ]; then
		read -p "Replace directory '$2' with symlink to '$1? " yn
		case $yn in
			y) rm -rf $2 ;;
			*) return 1 ;;
		esac
	fi
	ln -s $PWD/$1 $2
}

mkdir -p $HOME/.config/kak
mkdir -p $HOME/.config/kak/colors
mkdir -p $HOME/.config/kak/plugins

pushd $HOME/.config/kak/plugins
git clone https://github.com/andreyorst/plug.kak.git plug.kak
popd

prompt_to_replace bashrc      $HOME/.bashrc
prompt_to_replace inputrc     $HOME/.inputrc
prompt_to_replace tmux.conf   $HOME/.tmux.conf
prompt_to_replace tmux.local  $HOME/.tmux.local
prompt_to_replace tmux.remote $HOME/.tmux.remote
prompt_to_replace gdbinit     $HOME/.gdbinit
prompt_to_replace conkyrc     $HOME/.conkyrc
prompt_to_replace kakrc       $HOME/.config/kak/kakrc
prompt_to_replace mono.kak    $HOME/.config/kak/colors/mono.kak
