#!/bin/bash

# Environment variables used for configuration:
#       ENABLE_ATTRIBUTES
#       ENABLE_COLOR
#       ENABLE_RGB

FG_BLACK=30
FG_DARK_RED=31
FG_DARK_GREEN=32
FG_BROWN=33
FG_DARK_BLUE=34
FG_DARK_MAGENTA=35
FG_DARK_CYAN=36
FG_GRAY=37
FG_BLACK=40
FG_DARK_GRAY=90
FG_RED=91
FG_GREEN=92
FG_YELLOW=93
FG_BLUE=94
FG_MAGENTA=95
FG_CYAN=96
FG_WHITE=97
BG_BLACK=40
BG_RED=41
BG_GREEN=42
BG_BROWN=43
BG_BLUE=44
BG_MAGENTA=45
BG_CYAN=46
BG_LITE_GRAY=47
BG_GRAY=100
BG_LITE_RED=101
BG_LITE_GREEN=102
BG_YELLOW=103
BG_LITE_BLUE=104
BG_LITE_MAGENTA=105
BG_LITE_CYAN=106
BG_WHITE=107

if [ ! -z "$ENABLE_ATTRIBUTES" ]; then
	function bold()   { printf "\e[1m"; }
	function italic() { printf "\e[3m"; }
	function under()  { printf "\e[4m"; }
	function strike() { printf "\e[9m"; }
	function norm()   { printf "\e[0m"; }
else
	function bold()   { :; }
	function italic() { :; }
	function under()  { :; }
	function strike() { :; }
	function norm()   { :; }
fi

if [ ! -z "$ENABLE_COLOR" ]; then
	# Accepts one of the above values as arg 1
	function color() { printf "\e[$1m"; }
else
	function color() { :; }
fi

if [ -z "$ENABLE_RGB" ] || [ -z "$ENABLE_COLOR" ]; then
	function color_rgb() { :; }
	function redefcol() { :; }
	function redefbg() { :; }
	function redeffg() { :; }
else

	# If we make it here, we have true color
	function color_rgb() { printf "\e[38;2;$1;$2;$3m"; }

	# This escape code was difficult to search for. Found it here:
	# https://metacpan.org/release/Term-ExtendedColor-Xresources/source/lib/Term/ExtendedColor/Xresources.pm
	# Remaps an xterm 256 color index to a new RGB value
	# redefcol <index> <rgb>
	# where r, g, and b are 2 digit hex values
	redefcol() {
		case $TERM in
			*tmux*|*screen*)
				echo -ne "\eP\e]4;$1;rgb:${2:0:2}/${2:2:2}/${2:4:2}\a\e\\"
				;;
			*)
				echo -ne "\e]4;$1;rgb:${2:0:2}/${2:2:2}/${2:4:2}\e\\"
				;;
		esac
	}
	redefbg() {
		case $TERM in
			*tmux*|*screen*)
				echo -ne "\eP\e]11;rgb:${1:0:2}/${1:2:2}/${1:4:2}\a\e\\"
				;;
			*)
				echo -ne "\e]11;rgb:${1:0:2}/${1:2:2}/${1:4:2}\e\\"
				;;
		esac

	}
	redeffg() {
		case $TERM in
			*tmux*|*screen*)
				echo -ne "\eP\e]10;rgb:${1:0:2}/${1:2:2}/${1:4:2}\a\e\\"
				;;
			*)
				echo -ne "\e]10;rgb:${1:0:2}/${1:2:2}/${1:4:2}\e\\"
				;;
		esac
	}
fi
