#!/bin/bash

if [ ! -z "$ENABLE_UNICODE" ]; then
	export PROMPT_TEXT="  "

	export CLOCK_ICON=""
	export CALENDAR_ICON=""
	export FOLDER_ICON=""
	export HOME_ICON=""
	export SERVER_ICON=""
	export NETWORK_ICON=""
	export TEMPERATURE_ICON="宅"
	export LOCK_ICON=""
	export PREFIX_ICON=""
	export ZOOM_ICON=""
	export SYNC_ICON="⥱"
	export GIT_ICON=""
	export LINE_ICON=""
	export COLUMN_ICON=""

	export POWERLINE_FILLED_LEFT=""
	export POWERLINE_FILLED_RIGHT=""
	export POWERLINE_LEFT=""
	export POWERLINE_RIGHT=""
else
	export PROMPT_TEXT=" $ "

	export CLOCK_ICON=""
	export CALENDAR_ICON=""
	export FOLDER_ICON=""
	export HOME_ICON="~"
	export SERVER_ICON=""
	export NETWORK_ICON=""
	export TEMPERATURE_ICON="F"
	export LOCK_ICON="L"
	export PREFIX_ICON="!"
	export ZOOM_ICON="Z"
	export SYNC_ICON="S"
	export GIT_ICON=""
	export LINE_ICON="L"
	export COLUMN_ICON="C"

	export POWERLINE_FILLED_LEFT="<"
	export POWERLINE_FILLED_RIGHT=">"
	export POWERLINE_LEFT="<"
	export POWERLINE_RIGHT=">"
fi
