#!/bin/bash
source colorutils

redefbg 1C1C1C
redeffg D1CFD0

# redefcol 0  2F2E2C 
# redefcol 1  D78788 
# redefcol 2  AFBDA3
# redefcol 3  E4C8AD
# redefcol 4  A2BDCE
# redefcol 5  D7BEDB
# redefcol 6  AFE8DD
# redefcol 7  D1CFD0
# redefcol 8  494844 
# redefcol 9  A26567 
# redefcol 10 90A57E
# redefcol 11 D6AF86
# redefcol 12 7EA5BC
# redefcol 13 C59EC3
# redefcol 14 8ADAB3
# redefcol 15 EFEFEF
redefcol 0  2F2E2C 
redefcol 1  D78788 
redefcol 2  AFBDA3
redefcol 3  E4C8AD
redefcol 4  6bb5f2 #47c6fc #A2BDCE
redefcol 5  D7BEDB
redefcol 6  81b3bd #569A9D #AFE8DD
redefcol 7  D1CFD0
redefcol 8  898884 
redefcol 9  A26567 
redefcol 10 7e8964 #90A57E
redefcol 11 D6AF86
redefcol 12 2f7cc3# 7EA5BC
redefcol 13 C59EC3
redefcol 14 528090 #8ADAB3
redefcol 15 EFEFEF

