#!/bin/bash

export PROMPT_TEXT="  "
export RUNNING_ICON=""
export CLOCK_ICON=""
export CALENDAR_ICON=""
export FOLDER_ICON="   "
export HOME_ICON=""
export SERVER_ICON="  "
export NETWORK_ICON=""
export TEMPERATURE_ICON="宅"
export LOCK_ICON=""
export PREFIX_ICON=""
export ZOOM_ICON=""
export SYNC_ICON="⥱"
export GIT_ICON=""
export LINE_ICON=""
export COLUMN_ICON=""
export POWERLINE_FILLED_LEFT=""
export POWERLINE_FILLED_RIGHT=""
export POWERLINE_LEFT=""
export POWERLINE_RIGHT=""
